# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Enviar a internal testing"
    lane :internal do
        gradle(task: 'bundle', build_type: 'Release')
        upload_to_play_store(track: 'internal', skip_upload_apk: true)
    end

    desc "Enviar Beta Build a Google Play Store"
    lane :beta do
        gradle(task: 'bundle', build_type: 'Release')
        upload_to_play_store(track: 'beta', skip_upload_apk: true)
    end

    desc "Enviar Beta a Firebase"
    lane :firebase do
        gradle(task: 'assemble', build_type: 'Release')
    
        firebase_app_distribution()
    end
end
